import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Split into one sidebar per top navbar section instead of a single sidebar
 * spanning the whole docs/ tree. Docusaurus marks a navbar item active by
 * checking whether the current page belongs to that item's target sidebar
 * — with one shared sidebar, every navbar item lit up as active on every
 * docs page. Scoping each section to its own sidebar id fixes that.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'autogenerated', dirName: 'Getting Started'},
    {type: 'autogenerated', dirName: 'Api'},
  ],
  modelSidebar: [{type: 'autogenerated', dirName: 'Model'}],
  whySidebar: [{type: 'autogenerated', dirName: 'Why'}],
  conceptsSidebar: [{type: 'autogenerated', dirName: 'Concepts'}],
};

export default sidebars;
